# Generated by Django 3.2 on 2023-02-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель продукта'),
        ),
    ]
