# Generated by Django 3.2 on 2023-02-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Фото'),
        ),
    ]
